# Generated by Django 4.1 on 2023-05-14 10:42

import _socket
from django.db import migrations, models
import somans_models.models.audit_model_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=somans_models.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=somans_models.models.audit_model_mixin.utcnow)),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('personnel_number', models.CharField(max_length=45, null=True, verbose_name='Personnel number')),
                ('last_name', models.CharField(max_length=45, null=True, verbose_name='Lastname')),
                ('first_name', models.CharField(max_length=45, null=True, verbose_name='Firstname')),
                ('personnel_area_text', models.CharField(max_length=45, null=True, verbose_name='Personnel Area text')),
                ('name_of_ee_subgroup', models.CharField(max_length=45, null=True, verbose_name='Name of EE subgroup')),
                ('cost_center', models.CharField(max_length=15, null=True, verbose_name='Cost center')),
                ('cost_center_name', models.CharField(max_length=45, null=True, verbose_name='Cost center name')),
            ],
            options={
                'verbose_name': 'Headcount',
                'verbose_name_plural': 'Headcount',
            },
        ),
    ]
