from .software_dashboard_view import SoftwareDashboardView
from .server_dashboard_view import ServerDashboardView
from .workstation_dashboard_view import WorkstationDashboardView
from .new_software_workstation import NewWorkstationSoftwareView
from .new_software_server import NewServerSoftwareView
from .server_details_view import ServerDetailsView
from .workstation_details import WorkstationDetailsView

