from .software_dashboard_view import SoftwareDashboardView
from .server_dashboard_view import ServerDashboardView
from .workstation_dashboard_view import WorkstationDashboardView
from .new_software_workstation import NewWorkstationSoftwareView
from .new_software_server import NewServerSoftwareView
from .server_details_view import ServerDetailsView
from .workstation_details import WorkstationDetailsView
from .list_of_server import ListOfServerView
from .list_of_workstation import ListOfWorkstationView
from .server_list_vs_installed import ServerListVsInstalledView
from .workstation_list_vs_installed import WorkstationListVsInstalledView
from .list_workstation_duplicate import ListOfWorkstationDuplicateView
from .list_server_duplicate import ListOfServerDuplicateView
from .ls_wks_dup_details import ListWorkstationDuplicateDetailsView




