# Generated by Django 4.1 on 2023-07-17 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0002_approvesoftware_requester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvesoftware",
            name="requester_date",
            field=models.DateField(
                default=datetime.date(2023, 7, 17), verbose_name="Requester Date"
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovesoftware",
            name="requester_date",
            field=models.DateField(
                default=datetime.date(2023, 7, 17), verbose_name="Requester Date"
            ),
        ),
    ]
