# Generated by Django 4.1 on 2023-07-17 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0003_approvesoftware_requester_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvesoftware",
            name="requester_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Requester Date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapprovesoftware",
            name="requester_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Requester Date"
            ),
        ),
    ]
