# Generated by Django 4.1 on 2023-07-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0005_approvesoftware_approve_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvesoftware",
            name="approve_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approve Date"),
        ),
        migrations.AlterField(
            model_name="historicalapprovesoftware",
            name="approve_datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approve Date"),
        ),
    ]
