# Generated by Django 4.1 on 2023-07-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0006_alter_approvesoftware_approve_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvesoftware",
            name="device_permission",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Have you review all devices which this software is installed and ensure that they have permission to use this product?",
            ),
        ),
        migrations.AddField(
            model_name="approvesoftware",
            name="reasons",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reasons for this request"
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovesoftware",
            name="device_permission",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Have you review all devices which this software is installed and ensure that they have permission to use this product?",
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovesoftware",
            name="reasons",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reasons for this request"
            ),
        ),
    ]
