# Generated by Django 4.1 on 2023-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0007_approvesoftware_device_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvesoftware",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="historicalapprovesoftware",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Status"),
        ),
    ]
