# Generated by Django 4.1 on 2023-07-19 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0008_alter_approvesoftware_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="approvesoftware",
            old_name="device_permission",
            new_name="devices_permitted",
        ),
        migrations.RenameField(
            model_name="historicalapprovesoftware",
            old_name="device_permission",
            new_name="devices_permitted",
        ),
    ]
