# Generated by Django 4.1 on 2023-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "somans_dashboard",
            "0009_rename_device_permission_approvesoftware_devices_permitted_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="approvesoftware",
            name="approve_review",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Did you briefly review this request?",
            ),
        ),
        migrations.AddField(
            model_name="approvesoftware",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Additional Comments"),
        ),
        migrations.AddField(
            model_name="historicalapprovesoftware",
            name="approve_review",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="Did you briefly review this request?",
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovesoftware",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Additional Comments"),
        ),
    ]
