# Generated by Django 4.1 on 2023-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0011_alter_approvesoftware_approve_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvesoftware",
            name="next_url",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Redirect to?"
            ),
        ),
        migrations.AddField(
            model_name="historicalapprovesoftware",
            name="next_url",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Redirect to?"
            ),
        ),
    ]
