# Generated by Django 4.1 on 2023-07-20 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("somans_dashboard", "0012_approvesoftware_next_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="approvesoftware",
            old_name="next_url",
            new_name="next_url_name",
        ),
        migrations.RenameField(
            model_name="historicalapprovesoftware",
            old_name="next_url",
            new_name="next_url_name",
        ),
    ]
