# Generated by Django 4.1 on 2023-09-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idap_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationlinks",
            name="app_link",
            field=models.TextField(verbose_name="Application Link"),
        ),
        migrations.AlterField(
            model_name="historicalapplicationlinks",
            name="app_link",
            field=models.TextField(verbose_name="Application Link"),
        ),
    ]
