# Generated by Django 4.1 on 2023-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idap_finservices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finservicesprod",
            name="Trswift_TZ",
            field=models.CharField(default="", max_length=6, verbose_name="Trswift-TZ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finservicesprod",
            name="Uplpsmsg_TZ",
            field=models.CharField(default="", max_length=6, verbose_name="Uplpsmsg-TZ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finservicesprodhistory",
            name="Trswift_TZ",
            field=models.CharField(default="", max_length=6, verbose_name="Trswift-TZ"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finservicesprodhistory",
            name="Uplpsmsg_TZ",
            field=models.CharField(default="", max_length=6, verbose_name="Uplpsmsg-TZ"),
            preserve_default=False,
        ),
    ]
