# Generated by Django 4.1 on 2023-08-03 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("idap_finservices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finservicesprod",
            name="fin_timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Timestamp"
            ),
        ),
    ]
