# Generated by Django 4.1 on 2023-08-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idap_finservices", "0002_alter_finservicesprod_fin_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finservicesprod",
            name="fin_timestamp",
            field=models.CharField(max_length=45, verbose_name="Timestamp"),
        ),
    ]
