# Generated by Django 4.1 on 2023-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idap_finservices", "0003_finservicestimer"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinServicesTimerNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_run", models.DateTimeField(verbose_name="Last Run")),
            ],
        ),
    ]
