# Generated by Django 4.1 on 2023-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idap_finservices", "0003_alter_finservicesprod_fin_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinServicesProdHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ConfigService",
                    models.CharField(max_length=6, verbose_name="ConfigService"),
                ),
                (
                    "FINRPT_finlstclnt",
                    models.CharField(max_length=6, verbose_name="FINRPT-finlstclnt"),
                ),
                (
                    "FINRPT_comnclnt",
                    models.CharField(max_length=6, verbose_name="FINRPT-comnclnt"),
                ),
                ("CBC", models.CharField(max_length=6, verbose_name="CBC")),
                ("Finlistval", models.CharField(max_length=6, verbose_name="Finlistval")),
                ("Coresession", models.CharField(max_length=6, verbose_name="Coresession")),
                ("Referral", models.CharField(max_length=6, verbose_name="Referral")),
                ("Uniser_TZ", models.CharField(max_length=6, verbose_name="Uniser-TZ")),
                (
                    "MQMSwiftIn_TZ",
                    models.CharField(max_length=6, verbose_name="MQMSwiftIn-TZ"),
                ),
                (
                    "MQMSwiftOut_TZ",
                    models.CharField(max_length=6, verbose_name="MQMSwiftOut-TZ"),
                ),
                ("MQMRtgsIn_TZ", models.CharField(max_length=6, verbose_name="MQMRtgsIn-TZ")),
                (
                    "MQMRtgsOut_TZ",
                    models.CharField(max_length=6, verbose_name="MQMRtgsOut-TZ"),
                ),
                ("MQMRead_TZ", models.CharField(max_length=6, verbose_name="MQMRead-TZ")),
                (
                    "Dispatcher_TZ",
                    models.CharField(max_length=6, verbose_name="Dispatcher-TZ"),
                ),
                ("Binagent_TZ", models.CharField(max_length=6, verbose_name="Binagent-TZ")),
                ("Swiftsrv_TZ", models.CharField(max_length=6, verbose_name="Swiftsrv-TZ")),
                ("Pmssrv_TZ", models.CharField(max_length=6, verbose_name="Pmssrv-TZ")),
                ("Genlimo_TZ", models.CharField(max_length=6, verbose_name="Genlimo-TZ")),
                ("Aabsrv_TZ", models.CharField(max_length=6, verbose_name="Aabsrv-TZ")),
                ("Eabgst_TZ", models.CharField(max_length=6, verbose_name="Eabgst-TZ")),
                ("fin_timestamp", models.CharField(max_length=45, verbose_name="Timestamp")),
                ("node", models.IntegerField(default=0, verbose_name="Node")),
            ],
        ),
    ]
